### ISSUE TITLE
Instance loses NIC after sdc-migrate - again

### ISSUE THREAD

**Issue by teutat3s** [joyent/sdc-net-agent#3]
Just experienced this in our DC with PI `20190912T054018Z` and `net-agent@2.3.1`:

Steps to reproduce:

1. Set a tag on an instance
2. migrate the instance to another CN
3. finalize 
4. remove the tag

Here net-agent logs the following (duplicates removed):
```
{
    "name": "net-agent",
    "hostname": "cn03",
    "pid": 9497,
    "component": "instance",
    "uuid": "62ce42b8-048b-6eb3-e36f-ad7b3a3e2a24",
    "level": 30,
    "msg": "Removing NIC 90:b8:d0:14:b2:13 on VM 62ce42b8-048b-6eb3-e36f-ad7b3a3e2a24",
    "time": "2019-09-25T19:55:50.855Z",
    "v": 0
} {
    "name": "net-agent",
    "hostname": "cn03",
    "pid": 9497,
    "component": "vmadm-events",
    "level": 20,
    "msg": "VM 62ce42b8-048b-6eb3-e36f-ad7b3a3e2a24 fields updated (nics.*) - setting needsUpdate",
    "time": "2019-09-25T19:55:51.269Z",
    "v": 0
} {
    "name": "net-agent",
    "hostname": "cn03",
    "pid": 9497,
    "level": 30,
    "num_vms": 6,
    "msg": "updateVMs",
    "time": "2019-09-25T19:55:51.270Z",
    "v": 0
} {
    "name": "net-agent",
    "hostname": "cn03",
    "pid": 9497,
    "component": "instance",
    "uuid": "62ce42b8-048b-6eb3-e36f-ad7b3a3e2a24",
    "level": 30,
    "msg": "NIC 90:b8:d0:14:b2:13 removed from VM 62ce42b8-048b-6eb3-e36f-ad7b3a3e2a24",
    "time": "2019-09-25T19:55:51.270Z",
    "v": 0
} {
    "name": "net-agent",
    "hostname": "cn03",
    "pid": 9497,
    "component": "instance",
    "uuid": "62ce42b8-048b-6eb3-e36f-ad7b3a3e2a24",
    "level": 30,
    "payload": {
        "uuid": "62ce42b8-048b-6eb3-e36f-ad7b3a3e2a24",
        "resolvers": [],
        "set_routes": {},
        "remove_routes": []
    },
    "msg": "Updating networking information for VM",
    "time": "2019-09-25T19:55:51.273Z",
    "v": 0
} {
    "name": "net-agent",
    "hostname": "cn03",
    "pid": 9497,
    "component": "instance",
    "uuid": "62ce42b8-048b-6eb3-e36f-ad7b3a3e2a24",
    "level": 30,
    "msg": "Rebooting VM 62ce42b8-048b-6eb3-e36f-ad7b3a3e2a24",
    "time": "2019-09-25T19:55:51.630Z",
    "v": 0
} {
    "name": "net-agent",
    "hostname": "cn03",
    "pid": 9497,
    "level": 30,
    "num_vms": 6,
    "msg": "updateVMs",
    "time": "2019-09-25T19:55:51.630Z",
    "v": 0
} {
    "name": "net-agent",
    "hostname": "cn03",
    "pid": 9497,
    "component": "vmadm-events",
    "level": 20,
    "msg": "VM 62ce42b8-048b-6eb3-e36f-ad7b3a3e2a24 fields updated (resolvers.*,resolvers.*) - setting needsUpdate",
    "time": "2019-09-25T19:55:51.841Z",
    "v": 0
} {
    "name": "net-agent",
    "hostname": "cn03",
    "pid": 9497,
    "component": "instance",
    "uuid": "62ce42b8-048b-6eb3-e36f-ad7b3a3e2a24",
    "level": 30,
    "payload": {
        "uuid": "62ce42b8-048b-6eb3-e36f-ad7b3a3e2a24",
        "resolvers": [],
        "set_routes": {},
        "remove_routes": []
    },
    "msg": "Updating networking information for VM",
    "time": "2019-09-25T19:55:51.915Z",
    "v": 0
} {
    "name": "net-agent",
    "hostname": "cn03",
    "pid": 9497,
    "component": "vmadm-events",
    "level": 20,
    "msg": "VM 62ce42b8-048b-6eb3-e36f-ad7b3a3e2a24 fields updated (state) - setting needsUpdate",
    "time": "2019-09-25T19:55:52.733Z",
    "v": 0
} {
    "name": "net-agent",
    "hostname": "cn03",
    "pid": 9497,
    "component": "nic",
    "mac": "90:b8:d0:14:b2:13",
    "level": 30,
    "msg": "Stopped tracking NIC",
    "time": "2019-09-25T19:55:54.450Z",
    "v": 0
} {
    "name": "net-agent",
    "hostname": "cn03",
    "pid": 9497,
    "level": 30,
    "num_vms": 6,
    "msg": "updateVMs",
    "time": "2019-09-25T19:55:54.451Z",
    "v": 0
}
```

And somehow all NICs on that instance disappear. I'd be happy if I can be of any help to debug this further.

EDIT: on another instance the NICs got removed without the tag add/remove action, so maybe it's just the finalize? that instance's UUID is: `40659ae0-0328-ed41-db18-d484f80b0361`

Filtered logs in this gist - I'll guess we'll need more log space here.
https://gist.github.com/teutat3s/646a8ffcbcb71515f84ed23feb2b649f

**Comment by twhiteman** [comment]
That's not good - can you add more information, such as:
```
sdc-migrate get 62ce42b8-048b-6eb3-e36f-ad7b3a3e2a24    # to show action times and servers
sdc-server list    # to correlate name to uuid
```
and the relevant net-agent logs from the other cn as well.

Note: I'm assuming all compute nodes are using the same version of net-agent (net-agent@2.3.1).

**Comment by teutat3s** [comment]
> Note: I'm assuming all compute nodes are using the same version of net-agent (net-agent@2.3.1).

This should be the case - at least `sdcadm insts` says so. Is there a way to double check the version on the cn? because the agents were updated recently - but they shouldn't need any further interaction after `sdcadm experimental update`, right?

**Comment by twhiteman** [comment]
Right (sdcadm experimental update should be all that is needed, but), to double check - you can check using these commands on each compute node in question:
```
grep version /opt/smartdc/agents/lib/node_modules/net-agent/package.json   # should be 2.3.1
ls -la /opt/smartdc/agents/lib/node_modules/net-agent/package.json   # show last modified timestamp - i.e. when it was last updated
ps auxww | grep net-agent    # check the start time of the process (it should be later than the file last modified)
```

**Comment by teutat3s** [comment]
confimed the version. Here is the gist with the hopefully helpful log files. If you need more - please tell me. 
https://gist.github.com/teutat3s/646a8ffcbcb71515f84ed23feb2b649f


CN UUIDs
```
CN03 - 5fa3d414-b0ec-11de-92ad-00215ec81a1c
CN06 - 7a3b1a1c-b456-e411-afba-40f2e972d172
```

I did `sdc-migrate finalize` before the NICs got lost, so I can't provide the timestamps from there, would you like screenshots or logs of the workflows?

**Comment by teutat3s** [comment]
Saw your PR on https://cr.joyent.us/#/c/6932/ - nice and fast response! 

I have another question regarding sdc-migrate: 

somehow a migration record managed to sneak in that has the same source and target cn - now I'm unable to `finalize` or `abort` it and am basically unable to migrate that instance with `sdc-migrate` 
Is there a manual way to delete that false migration record?

**Comment by twhiteman** [comment]
That PR is not 100% yet (I think there may yet be issues with that line of simplification - or maybe it needs to be simplified even more).

For a stuck migration - there is not yet a way to force delete that record using the cli (or VMAPI) interface - which is rather annoying. For this, you'll need to resort to using moray (or manatee) to find/delete the offending `vmapi_vm_migrations` record, key'ing on the `source_server_uuid` string.
